# Generated by Django 2.0.2 on 2019-06-05 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paste', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='created_on',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='paste',
            name='updated_on',
            field=models.DateTimeField(),
        ),
    ]
